CREATE DATABASE node;

USE node;

CREATE TABLE usuarios (
  id VARCHAR(36) PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  
);

CREATE TABLE items (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    user_id VARCHAR(36),
    FOREIGN KEY (user_id) REFERENCES usuarios(id),
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE chats (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    user_id VARCHAR(36),
    FOREIGN KEY (user_id) REFERENCES usuarios(id),
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE dados (
    id VARCHAR(36) PRIMARY KEY,
    name TEXT,
    idade TEXT,
    sexo  TEXT,
    cidade TEXT,
    telefone TEXT,
    user_id VARCHAR(36),
    FOREIGN KEY (user_id) REFERENCES usuarios(id),
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE dadosimgs (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    tipo_mime VARCHAR(255) NOT NULL,
    tamanho INT NOT NULL,
    dados_imagem LONGBLOB NOT NULL,
    data_upload TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id VARCHAR(36),
    FOREIGN KEY (user_id) REFERENCES usuarios(id),
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE transacoes (
  id VARCHAR(36) PRIMARY KEY,
  paypal_transaction_id VARCHAR(255) NOT NULL,
  create_time DATETIME NOT NULL,
  state VARCHAR(255) NOT NULL,
  payer JSON NOT NULL,
  transactions JSON NOT NULL,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL,
  user_id VARCHAR(36),
  FOREIGN KEY (user_id) REFERENCES usuarios(id)

);


ALTER TABLE items
ADD COLUMN user_id INT NOT NULL;

